"""
voronoi.py
----------

Voronoi-based Spatial Partitioning Utilities for 3D Particle Simulations

This module provides utility functions for computing weighted Voronoi tessellations
in 3D periodic domains. It focuses on computational efficiency through adaptive
block sizing based on particle density. This is useful for scientific computing
workflows involving spatial decomposition, particle simulations, and geometric analysis.

Key functionalities:
- Optimal Block Size Calculation: Dynamically determines a suitable block size 
  for Voronoi computation based on particle number, simulation box dimensions, 
  and desired particle density per block.
- Weighted Voronoi Tessellation: Generates Voronoi cells in 3D space with periodic 
  boundary conditions, supporting radius-based weighting for accurate partitioning.

Dependencies:
- NumPy: Efficient numerical computations for volume, density, and scaling calculations.
- PyVoro: Python interface to Voro++ for high-performance Voronoi tessellation.

Use case:
Integrate this module into simulation pipelines to improve computational performance
and accuracy in geometry-driven data analysis, particularly for systems requiring
periodic boundary conditions.

"""

import numpy as np
import pyvoro


def calculate_optimal_block_size(positions, box_dimensions, target_particles_per_block=50, 
                                 min_block_factor=1/20, max_block_factor=1/5):
    """
    Determine an optimal block size for Voronoi tessellation based on particle density.

    Parameters
    ----------
    positions : array_like
        Array of particle positions with shape (N, 3), where N is the number of particles.
    box_dimensions : array_like
        Lengths of the simulation box along each axis [Lx, Ly, Lz].
    target_particles_per_block : int, optional
        Desired number of particles per Voronoi block (default is 50).
    min_block_factor : float, optional
        Minimum fraction of the smallest box dimension allowed for a block size (default is 1/20).
    max_block_factor : float, optional
        Maximum fraction of the smallest box dimension allowed for a block size (default is 1/5).

    Returns
    -------
    float
        Optimal block size clipped within the specified min and max limits.
    """
    # Compute the total volume of the simulation box
    total_volume = np.prod(box_dimensions)

    # Estimate particle density
    particle_density = len(positions) / total_volume

    # Compute target block volume based on desired particles per block
    target_block_volume = target_particles_per_block / particle_density

    # Convert volume to cubic block size
    optimal_block_size = np.cbrt(target_block_volume)

    # Enforce minimum and maximum block size limits
    min_block_size = min(box_dimensions) * min_block_factor
    max_block_size = min(box_dimensions) * max_block_factor

    # Return the block size constrained within limits
    return np.clip(optimal_block_size, min_block_size, max_block_size)


def compute_weighted_voronoi_cells(points, box_limits, block_size, particle_radii):
    """
    Compute a weighted Voronoi tessellation for 3D points using PyVoro with periodic boundaries.

    Parameters
    ----------
    points : array_like
        Array of particle positions with shape (N, 3).
    box_limits : array_like
        Bounds of the simulation box [[x_min, x_max], [y_min, y_max], [z_min, z_max]].
    block_size : float
        Size of each computational block used by PyVoro.
    particle_radii : array_like
        Array of particle radii used for weighted tessellation.

    Returns
    -------
    list of dict
        Voronoi cells generated by PyVoro, each represented as a dictionary with
        geometric information.

    Raises
    ------
    RuntimeError
        If Voronoi computation fails.
    """
    try:
        # Compute Voronoi cells with periodic boundary conditions in all axes
        voronoi_cells = pyvoro.compute_voronoi(
            points,
            box_limits,
            block_size,
            periodic=[True, True, True],
            radii=particle_radii
        )
    except Exception as exc:
        raise RuntimeError(f"Error during Voronoi tessellation: {exc}")

    return voronoi_cells
